Ls/11/a2   markup a readme
selsa-inube/bootcamp-feb pull request #73
Opened 2024-02-07 15:20 UTC by luisalejandrosalazar

Activity 11 "A2 - markup a readme" completed.

2024-02-07 18:44 UTC, carin91 requested changes

2024-02-07 18:44 UTC, carin91 commented on src/ls/markup-readme.html
> +        <hr />
Avoid the use of the hr in any case, you should guarantee spacing and presentation through the properties of the containers or other ways of spacing.

2024-02-07 18:46 UTC, luisalejandrosalazar commented on src/ls/markup-readme.html
> +        <hr />
In this case the hr tag is used to draw a line under h2 tags.

2024-02-20 10:16 UTC, carin91 approved these changes

2024-02-20 10:16 UTC, merged