Activity #29 - A17P Sidebar completed
selsa-inube/bootcamp-feb pull request #75
Opened 2024-02-14 16:55 UTC by luisalejandrosalazar

2024-03-02 12:41 UTC, carin91 requested changes
Good Job!

However, several changes are required.

2024-03-02 12:41 UTC, carin91 commented on src/ls/html-css/sidebar/styles.css
> +/* #menu1 {
Do not leave commented code.

2024-03-02 12:41 UTC, carin91 commented on src/ls/html-css/sidebar/styles.css
> +  background-color: #f1e9fc;
I understand that the picture is not totally clear. However, i would expect that the color and icon for the #teams-menu sections appears for the :active element. Refactor to adjust that.

2024-03-02 12:41 UTC, carin91 commented on src/ls/html-css/sidebar/styles.css
> +.tb-button::after {
You are including an icon in the DOM tree and based on the pseudoclass you are changing the display property to hide it. Can you refactor it to avoid the explicit creation of the element in the DOM TREE?.

Read: https://css-tricks.com/7-practical-uses-for-the-before-and-after-pseudo-elements-in-css/
Ref: (...) This effectively allows you to show something on a web page that might not be present in the HTML content (...)

2024-03-07 20:32 UTC, luisalejandrosalazar commented on src/ls/html-css/sidebar/index.html
> +          <li>
Corrected

2024-03-07 20:42 UTC, luisalejandrosalazar commented on src/ls/html-css/sidebar/styles.css
> +  display: flex;
Corrected.

2024-03-07 20:52 UTC, luisalejandrosalazar commented on src/ls/html-css/sidebar/styles.css
> +  margin: 0;
I added these default values because in my environment, some html elements have many values inherited from the 'user agent style sheet' that affect the display. Now I will try to summarize them. (We talked about this incident in one of our daily meetings)

2024-03-07 20:54 UTC, luisalejandrosalazar commented on src/ls/html-css/sidebar/styles.css
> +  position: relative;
Corrected

2024-03-07 20:55 UTC, luisalejandrosalazar commented on src/ls/html-css/sidebar/styles.css
> +.tb-button::after {
Corrected.

2024-03-07 21:03 UTC, luisalejandrosalazar commented on src/ls/html-css/sidebar/styles.css
> +/* #menu1 {
Corrected.

2024-03-08 00:10 UTC, luisalejandrosalazar commented on src/ls/html-css/sidebar/styles.css
> +  background-color: #f1e9fc;
Corrected.

2024-03-12 18:24 UTC, carin91 approved these changes

2024-03-12 18:24 UTC, merged