L5 activities completed
selsa-inube/bootcamp-feb pull request #83
Opened 2024-03-06 00:34 UTC by luisalejandrosalazar

2024-03-19 07:50 UTC, carin91 requested changes

2024-03-19 07:50 UTC, carin91 commented on src/ls/javascript/L5/3_everithing.js
> +  let result = true;
Is it needed? 
You should try to use less memory as possible and less CPU as possible.

Refactor this function to avoid the use of the result variable and using early returns.

2024-03-19 07:50 UTC, carin91 commented on src/ls/javascript/L5/4_dominant_writing_direction.js
> +const SCRIPTS = require("./scripts");
Check the functionality of this code, i got an error.

The SCRIPTS is not an array, is an object with a property called SCRIPTS. Check if your code runs or adjust that.

![image](https://github.com/selsa-inube/bootcamp-feb/assets/123512032/79a9fc3f-e1d1-41b6-b818-510dd7de0762)

2024-03-19 23:13 UTC, luisalejandrosalazar commented on src/ls/javascript/L5/3_everithing.js
> +  let result = true;
Fixed.

2024-03-19 23:13 UTC, luisalejandrosalazar commented on src/ls/javascript/L5/4_dominant_writing_direction.js
> +const SCRIPTS = require("./scripts");
Fixed.

2024-03-27 08:23 UTC, carin91 approved these changes

2024-03-27 08:23 UTC, merged