javascript l8 exercises completed
selsa-inube/bootcamp-feb pull request #85
Opened 2024-03-09 18:29 UTC by luisalejandrosalazar

2024-03-19 08:59 UTC, carin91 requested changes

2024-03-19 08:59 UTC, carin91 commented on src/ls/javascript/L8/1_Retry.js
> +      if (!(e instanceof MultiplicatorUnitFailure)) {
Refactor this:
(1) Is expected that the condition inside the if() statement gets a false value every time, so, you are not catching the errors that are an instanceof MultiplicatorUnitFailure
(2) Inside this scope you are throwing the error, that blocks the node operation.

Refactor it to log the error catch by the promise management.

2024-03-19 08:59 UTC, carin91 commented on src/ls/javascript/L8/2_The_locked_box.js
> +function withBoxUnlocked(body) {
Complete the exercise with the extra points:
For extra points, make sure that if you call withBoxUnlocked when the box is already unlocked, the box stays unlocked.

2024-03-20 16:36 UTC, luisalejandrosalazar commented on src/ls/javascript/L8/2_The_locked_box.js
> +function withBoxUnlocked(body) {
Added functionality

2024-03-20 17:19 UTC, luisalejandrosalazar commented on src/ls/javascript/L8/1_Retry.js
> +      if (!(e instanceof MultiplicatorUnitFailure)) {
MultiplicatorUnitFailure fails on average 80% of the time, the if statement, on line 16, is filtering those errors allowing MultiplicatorUnitFailure to be called again. It will show, or re-throw, an error only if it does not come from MultiplicatorUnitFailure. I understand that this is what is indicated in the exercise statement. "...The corresponding catch block should rethrow the exception when it is not an instance of MultiplicatorUnitFailure and ensure the call is retried when it is...."

2024-03-27 08:26 UTC, carin91 approved these changes

2024-03-27 08:26 UTC, merged