javascript l11 exercises completed
selsa-inube/bootcamp-feb pull request #87
Opened 2024-03-10 21:40 UTC by luisalejandrosalazar

2024-03-19 09:53 UTC, carin91 requested changes

2024-03-19 09:53 UTC, carin91 commented on src/ls/javascript/L11/1_Build_a_table.html
>      <meta charset="UTF-8" />
The prettier and packacge-lock.json files could not be updated. Delete any modifications on them.

I suggest creating a new branch and creating a new pull request because the package-lock.json is pretty hard to verify.

2024-03-19 09:53 UTC, carin91 commented on src/ls/javascript/L11/1_Build_a_table.html
> +      document.getElementById("mountains").appendChild(createTable(MOUNTAINS));
This is incomplete, complete the task including this:
(...)Once you have this working, right-align cells that contain number values by setting their style.textAlign property to "right"(...)

2024-03-19 09:53 UTC, carin91 commented on src/ls/javascript/L11/2_Elements_by_tag_name.html
> +        function countTags(node) {
Refactor to use a pure function outside byTagName

2024-03-20 20:39 UTC, luisalejandrosalazar commented on src/ls/javascript/L11/1_Build_a_table.html
> +      document.getElementById("mountains").appendChild(createTable(MOUNTAINS));
Exercise completed.

2024-03-20 20:39 UTC, luisalejandrosalazar commented on src/ls/javascript/L11/2_Elements_by_tag_name.html
> +        function countTags(node) {
refactorized function

2024-03-20 20:47 UTC, luisalejandrosalazar commented on src/ls/javascript/L11/1_Build_a_table.html
>      <meta charset="UTF-8" />
I created the ls/51 _**-2**_ /L11-Document-Object-Model branch and then I have pushed the exercise files there.

2024-03-27 08:28 UTC, closed without merging