feat: activity nyt in react completed
selsa-inube/bootcamp-feb pull request #90
Opened 2024-03-22 14:37 UTC by luisalejandrosalazar

2024-03-27 10:02 UTC, carin91 requested changes

2024-03-27 20:35 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleAnchor/styles.js
> +const StyledAnchor = styled.section`
Refactored.

2024-03-27 20:43 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleImage/index.jsx
> +    <StyledAnchor>
Refactored.

2024-03-27 21:17 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeA/styles.js
> +    font-family: Georgia, Times, "Times New Roman", serif;
Refactored.

2024-03-27 21:17 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeB/styles.js
> +    font-family: Georgia, Times, "Times New Roman", serif;
Refactored.

2024-03-27 21:17 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeB/styles.js
> +    font-family: Georgia, Times, "Times New Roman", serif;
Refactored.

2024-03-27 21:42 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeB/styles.js
> +const StyledSection = styled.section`
The ArticleTypeA and ArticleTypeB components have more differences than similarities.

Differences:
ArticleTypeA: img, h1, p.
ArticleTypeB: h2 

Similarities: CategoryButton and ArticleAnchor

The CategoryButton and ArticleAnchor components were created separately.

2024-03-27 23:41 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeC/styles.js
> +  & > section {
Refactored.

2024-03-27 23:43 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeC/styles.js
> +    font-family: Georgia, Times, "Times New Roman", serif;
Refactored.

2024-03-27 23:43 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeC/styles.js
> +    font-family: Georgia, Times, "Times New Roman", serif;
Refactored.

2024-03-27 23:44 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeD/index.jsx
> +    // <StyledSection>
Refactored.

2024-03-28 00:20 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/articleTypeD/styles.js
> +const StyledSection = styled.section`
The main difference between the ArticleTypeC and ArticleTypeD components is in the Grid layout of their components.

Also, components in those articles, such as h2 and p, have different fonts, sizes and colors. Even if you use the ArticleTypeC styles as a base, it would not make the code needed to import and change all those values unnecessarily complex?

2024-03-28 00:23 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/menuBar/barHeader/styles.js
> +    font-family: Arial, Helvetica, sans-serif;
The model fonts are different. For example, fonts of type D article are different from the other articles.

2024-03-28 03:35 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/menuBar/index.jsx
> +      <StyledUl style={{ width }}>
Refactored.

2024-03-28 03:40 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/common/pageIndicator/styles.js
> +const StyledAnchor = styled.section`
Refactored.

2024-03-28 03:40 UTC, luisalejandrosalazar commented on src/ls/react/A2P_NYT_in_react/src/components/footer/index.jsx
> +      <ArticleTypeD
Refactored.

2024-03-28 09:33 UTC, carin91 approved these changes

2024-03-28 09:33 UTC, merged